# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  # socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
  database: community_runner_development

test:
  <<: *default
  database: community_forum_test