development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://tgs-network.herokuapp.com/faye"
  secret_token: "d979661d0d93fd3bb98985dcf6b24dbb33b0da26369fe8597e7e647c76c807c5"
  signature_expiration: 3600 # one hour
